<?php

/**
 * @file
 * Contains user_badges.module..
 */

use Drupal\Core\Field\Plugin\Field\FieldType\EntityReferenceItem;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_badges_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_badges module.
    case 'help.page.user_badges':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User Badges module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_badges_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function user_badges_user_presave(Drupal\Core\Entity\EntityInterface $entity) {
  /** @var \Drupal\user\Entity\User $entity */
  // Keep non-role items and ten append each badge id to badge field.
  $field_item_list = $entity->get('field_user_badges');
  $field_item_list->filter(function (EntityReferenceItem $item) {
    return $item->get('entity')->getValue()->get('role_id')->isEmpty();
  });
  $badge_ids = \Drupal::entityTypeManager()->getStorage('badge')->getQuery()
    ->condition('role_id', $entity->getRoles(), 'IN')
    ->execute();
  foreach ($badge_ids as $id) {
    $field_item_list->appendItem($id);
  }
}
