<?php

/**
 * @file
 * Contains user_badges.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function user_badges_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the user_badges module.
    case 'help.page.user_badges':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('User Badges module.') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function user_badges_theme() {
  $theme = [];

  return $theme;
}

/**
 * Implements hook_ENTITY_TYPE_presave().
 */
function user_badges_user_presave(Drupal\Core\Entity\EntityInterface $entity) {
  $badges = array();
  $entity_manager = \Drupal::entityTypeManager();
  /** @var \Drupal\user\Entity\User $entity */
  $roles = $entity->getRoles();
  foreach ($roles AS $role) {
    $role_badge = $entity_manager->getStorage('badge')->loadByProperties(array('role_id' => $role));
    if (!empty($role_badge)) {
      $badges[] = $role_badge;
    }
    // $badges[] = array_values(\Drupal\user_badges\Entity\RoleBadge::getBadgeFromRole($role));
  }
  // Setting field value to NULL to prevent same value multiple times.
  $entity->get('field_user_badges')->setValue(NULL);

  // Getting field value and appending each badge id to badge field.
  $field_item_list = $entity->get('field_user_badges');
  foreach ($badges AS $id => $badge) {
    if (!empty($badge)) {
      /** @var \Drupal\user_badges\Entity\Badge $badge */
      $field_item_list->appendItem($badge[1]->id());
    }
  }
}
