user_badges.settings:
  type: mapping
  label: Settings
  mapping:
    user_badges_userweight:
      type: integer
    user_badges_selector_type:
      type: integer
    user_badges_role:
      type: integer
    user_badges_blocked_badge:
      type: integer
